STAGE 1a: >
  Hello! Since I am a ChatGPT-connected AI bot, I need to make sure you're OK
  with some ground rules before I can have fun conversations with you about
  goats. Or whatever you like talking about. But probably goats.

STAGE 1b: >
  Please go to https://ubr.world/aiyu and review the terms and conditions
  there. If you agree, please reply back to me with 'I agree'. Thanks!

STAGE 2: >
  Excellent! Thanks for reviewing. Your consent is logged and we can have
  conversations now! If you ever change your mind, please discontinue your
  interactions with me immediately. If something goes terribly wrong, please
  notify Raindog.