'UberWorld': >
    Sorry but ChatGPT doesn't know anything about UberWorld. If you want
    to learn more about it, you can explore the help files here or read about
    its history and development at: https://uberworld.org.
